### PR TITLE
Fix broken PO Box regexp

### PR DESCRIPTION
**Pull request by dkubb**
This branch fixes the broken PO Box regexp.

### CODE REVIEW

**Comment by dkubb** [comment]
@mbj this is ready for review.

**Comment by mbj** [comment]
@dkubb Heh, very good catch.

**Comment by mbj** [comment]
@dkubb What kind of mutation to the regexp could have forced us to specify the state of `Po` prefixed words?

**Comment by dkubb** [comment]
@mbj I'm not sure. Mutation testing can usually prove that the code you've written is fully specified, but it can't tell you if some functionality is missing.

In this specific case I think what we should've done is run through all the address lines in the database against the regexp and double checking that the addresses that are matched properly. I've been doing this to some degree this afternoon, but I want to do a full pass through all the address lines in the DB.

**Comment by dkubb** [comment]
@mbj I found another regexp change: #4

**Comment by mbj** [comment]
> @mbj I'm not sure. Mutation testing can usually prove that the code you've written is fully specified, but it can't tell you if some functionality is missing.

Yeah, this seems like a case where a semantic reducing mutation testing engine cannot find the black spot.

**Pull request merged**
